import express from 'express';
import MemberController from '../components/member.controller';
import asyncWrapper from '../utils/wrapper';
const router = express.Router();
router.post('/login', asyncWrapper(MemberController.login));
router.post('/create', asyncWrapper(MemberController.create));
router.post('/update/:id', asyncWrapper(MemberController.updateMember));
router.get('/list', asyncWrapper(MemberController.getList));
router.get('/refresh_token', asyncWrapper(MemberController.getAccessToken));
router.get('/logout', asyncWrapper(MemberController.logout));
export default router;
